nodes:
- input.visual:
    source: /Users/zaynesiew/Documents/SUTD/Competitions/National AI Student Challenge 2023/AISG_Challenge/raw_video_pipeline/raw_videos/video_230130_233205.mp4
- model.yolo
- model.posenet
- dabble.fps
- custom_nodes.dabble.movement
- draw.poses
- draw.legend:
    show: ["fps"]
- output.screen
- output.media_writer: # add new output node
        output_dir: analysed_videos
