nodes:
- input.visual:
    source: 0
- model.yolo
- model.posenet
- dabble.fps
- custom_nodes.dabble.movement
- draw.poses
- draw.legend:
    show: ["fps"]
- output.screen
- output.media_writer:  # add new output node
    output_dir: analysed_videos