nodes:

# Use live video feed, preferably from on-board webcam
- input.visual:
    source: 0
    resize:
        do_resizing: True
        width: 1920
        height: 1080

# Generate output video feed
- output.screen:
    window_name: "SpeakEase"
- output.media_writer:
    output_dir: raw_videos